web:
  image: nginx:1.13-alpine
  volumes:
   - ./default.conf.tmpl:/etc/nginx/conf.d/default.template
  ports:
   - "8080:80"
  environment:
   - NGINX_PORT=80
  command: /bin/sh "-c", "envsubst '$SHA_FOLDER' < default.conf.tmpl > /etc/nginx/conf.d/default.conf; nginx -g 'daemon off;'" 