web:
  image: nginx:1.13-alpine
  volumes:
   - ./conf.d:/etc/nginx/conf.d
   - ./honda:/usr/share/nginx/html
  ports:
   - "8080:80"
  environment:
   - NGINX_PORT=80
   - SHA_FOLDER=honda
  command: /bin/sh -c "nginx -g 'daemon off;'" 
 